output-class: AppLocalizations
arb-dir: lib/l10n
output-dir: lib/l10n_gen
template-arb-file: app_vi.arb
output-localization-file: app_localizations.dart
use-escaping: true
nullable-getter: false
suppress-warnings: true
untranslated-messages-file: desiredFileName.txt