name: women_diary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  json_annotation: ^4.8.1
  path_provider: ^2.0.11
  flutter_svg: ^2.0.9
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  cloud_firestore: ^6.0.2
  device_info_plus: ^12.1.0
  firebase_core: ^4.1.1
  fluttertoast: ^9.0.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.2
  cross_file: ^0.3.4+1
  video_player: ^2.8.6
  image_picker: ^1.1.0
  flutter_slidable: ^4.0.3
  store_redirect: ^2.0.2
  google_mobile_ads: ^6.0.0
  blur: ^4.0.0
  go_router: ^16.2.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  local_auth: ^2.3.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.0
  network_info_plus: ^7.0.0
  fl_chart: ^1.1.1
  table_calendar: ^3.2.0
  scrollable_positioned_list: ^0.3.8
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/png/

